/* take inspiration from this
 * https://planetmath.org/listofcommonlimits
 */

// Every page is an object.

// id will be auto-generated by a database (firebase maybe)

type LatexString = string
type MarkdownString = string
type IdString = string

type Page = {
  title: string
  id: IdString
  dependencies: IdString[]
  requiredFor: IdString[]
  claim: MarkdownString
  proof: MarkdownString
}
